### ISSUE TITLE
Combine all iPython notebooks

### ISSUE THREAD

**Issue by PandaWhoCodes** [cheenbeen/TextSummary#1]
Here are some tasks you can do combine all your iPython notebooks into a runnable applicaiton.

1. store the URLS in a urls.json file
2. create a main,py file that takes the urls from urls.json and starts parsing them
3. text_summarizer.py  - has functions for summarization - import that to main
4. db_functions.py - has functions to create a connection to db and store data to the Db - import into main
5. since you are extracting only 4 columns for each paper - have only one DB.

Running main.py will start parsing the server.

**Comment by PandaWhoCodes** [comment]
by url's i mean the RSS feed urls like
https://www.financialexpress.com/industry/banking-finance/feed

**Comment by sreenithibalasu** [comment]
So I was able to do steps 1 through 3

What I was not able to figure out, was how to connect the created DB from another file. (step 4)

Temporarily, I have the code for creating the DB in the main.ipynb file. I will find a solution for this ASAP.

**Comment by PandaWhoCodes** [comment]
Try using pymysql 
Use xampp to create a mysql db in windows 
Then just follow the documentation
